apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/abhitnc/argo-cd.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
